import { test, expect } from '@playwright/test';
import { localDemo, scenario } from './helpers';
import { randomUUID } from 'node:crypto';
import { validateClinicalAnalysis, type ClinicalAnalysisOutput } from '../../src/lib/ai/clinical-analysis';
import type { Transcript, RuntimeJob } from '../../src/lib/types';

test('analysis candidates require review, preserve zero, allow edits and explicit conflict replacement without re-running AI on refresh', async ({ page }) => {
  const envelope = await localDemo(page), { current_visit_id: visitId } = scenario(envelope,'A');
  const patientId = envelope.state.visits.find(v => v.id === visitId)!.patient_id;
  const text = '현재 발목 통증은 0점이에요. 약 효과가 걱정돼요.';
  const segmentId=randomUUID();
  const transcript: Transcript={id:randomUUID(),clinic_id:envelope.state.clinic.id,visit_id:visitId,revision:90,status:'reviewed',source_asset_key:'manual_seed',origin:'manual_demo',text,segments:[{id:segmentId,ordinal:1,speaker:'patient',text,start_ms:0,end_ms:3000}]};
  const evidence=[{segment_id:segmentId,quote:text}];
  const output: ClinicalAnalysisOutput={answers:[{item_key:'pain',subitem_key:'current_pain',text,change:null,temporal:'current',evidence}],measurements:[{item_key:'pain',subitem_key:'current_pain',instrument:'NRS',value:0,unit:'score',body_region:'ankle',laterality:'right',activity_key:null,measurement_context:'current_pain',temporal:'current',evidence}],signals:[{category:'worry',topic:'걱정',evidence}],missing_questions:[]};
  const result=validateClinicalAnalysis(output,transcript);
  const job: RuntimeJob={id:randomUUID(),clinic_id:envelope.state.clinic.id,visit_id:visitId,kind:'analysis',status:'waiting_review',stage:'clinical_analysis_review',input_hash:'synthetic-ui',created_at:'2026-10-09T01:00:00Z',updated_at:'2026-10-09T01:00:00Z',result:{task:'clinical_analysis',patientId,transcriptId:transcript.id,input_transcript_revision:90,stale_input:false,reviewed_signals:[],...result}};
  envelope.state.transcripts.push(transcript); envelope.state.jobs.push(job);
  let modelRequests=0;
  await page.route('**/api/state',route=>route.fulfill({json:envelope}));
  await page.route('**/api/clinical-analysis',route=>{modelRequests++;return route.fulfill({json:{jobId:job.id,reused:true}});});
  const requests: any[]=[];
  await page.route('**/api/clinical-analysis/review',route=>{
    const body=route.request().postDataJSON();requests.push(body);
    const candidate=result.candidates.find(c=>c.id===body.candidateId)!;
    if(candidate.kind==='answer' && body.decision==='confirm' && !body.allowOverwrite) return route.fulfill({status:409,json:{error:'기존 기록 확인 필요',code:'ANALYSIS_ENTRY_CONFLICT',details:{candidateId:candidate.id,targetHash:'current-hash',current:'의료진 직접 입력 3점'}}});
    candidate.status=body.decision==='confirm'?'confirmed':'rejected';envelope.version++;
    return route.fulfill({json:{saved:true,reused:false}});
  });
  await page.goto(`/clinic/visits/${visitId}`);
  await page.getByRole('tab',{name:'재진 질문',exact:true}).click();
  const region=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^전사 기반 진료 분석/})}).first();
  await expect(region.getByText('현재 통증 NRS 0점',{exact:true})).toBeVisible();
  const answer=region.getByRole('article').filter({hasNot:page.getByText('현재 통증 NRS 0점',{exact:true})}).filter({has:page.getByText('통증 · 현재 통증',{exact:true})});
  await answer.getByText('후보 직접 수정',{exact:true}).click();
  await answer.getByLabel('통증 · 현재 통증 후보 내용').fill('현재 통증 없음. 의료진 검토.');
  await answer.getByRole('button',{name:'확인 후 반영',exact:true}).click();
  await expect(answer.getByText('기존 의료진 기록: 의료진 직접 입력 3점',{exact:true})).toBeVisible();
  await answer.getByRole('button',{name:'현재 기록을 후보로 교체',exact:true}).click();
  await expect.poll(()=>requests.at(-1)).toMatchObject({decision:'confirm',allowOverwrite:true,expectedTargetHash:'current-hash',edit:{text:'현재 통증 없음. 의료진 검토.'},expectedTranscriptRevision:90});
  const metric=region.getByRole('article').filter({has:page.getByText('현재 통증 NRS 0점',{exact:true})});
  await metric.getByRole('button',{name:'확인 후 반영',exact:true}).click();
  await expect.poll(()=>requests.at(-1)?.candidateId).toBe(result.candidates.find(c=>c.kind==='measurement')!.id);
  const worry=region.getByRole('article',{name:'직접 표현한 걱정'});
  await worry.getByRole('button',{name:'후보 제외',exact:true}).click();
  await expect.poll(()=>requests.at(-1)).toMatchObject({decision:'reject'});
  await expect(region.getByText(/아직 전사 답변이 없는 항목/)).toBeVisible();
  await page.waitForTimeout(1500);expect(modelRequests).toBe(0);
  if(process.env.HANI_VISUAL_OUTPUT_DIR) await page.screenshot({path:`${process.env.HANI_VISUAL_OUTPUT_DIR}/clinical-analysis-review.png`,fullPage:true});
});
