import { expect, test } from '@playwright/test';
import { action, localDemo, readState, scenario } from './helpers';

test('stair ascent is beside pain and persists independently without inventing history or replacing input', async ({ page }) => {
  const initial = await localDemo(page);
  const { current_visit_id: visitId, patient_id: patientId } = scenario(initial,'A');
  const originalPain = initial.state.observations.filter(row => row.patient_id === patientId && row.instrument === 'NRS');
  await page.goto(`/clinic/visits/${visitId}`);
  const panel = page.getByRole('region', { name: '계단 오를 때 불편함', exact: true });
  await expect(panel).toBeVisible();
  await expect(panel.getByRole('img',{name:/계단 오를 때 불편함 경과/})).toBeVisible();
  await expect(panel.locator('.hs-nrs-summary > div').nth(1)).toContainText('4');
  const score = panel.getByLabel('오늘 확인한 불편 점수');
  await expect(score).toHaveValue('');
  await expect(panel.getByRole('button',{name:'저장',exact:true})).toBeDisabled();
  const positions = await page.locator('.hs-pain-functional-metrics > section').evaluateAll(elements => elements.map(element => { const r=element.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width}; }));
  expect(positions).toHaveLength(2); expect(positions[1].x).toBeGreaterThan(positions[0].x); expect(Math.abs(positions[0].y-positions[1].y)).toBeLessThan(2);
  await score.fill('0'); await panel.getByRole('button',{name:'저장',exact:true}).click();
  await expect(panel.getByRole('status')).toContainText('저장했어요');
  let state = await readState(page.request);
  const saved = state.state.observations.find(row => row.visit_id === visitId && row.activity_key === 'stairs_up')!;
  expect(saved).toMatchObject({ value:0, instrument:'APP_FUNCTION_DISCOMFORT',metric_key:'stair_ascent_discomfort',unit:'score',scale_min:0,scale_max:10,measurement_context:'stair_ascent_discomfort' });
  expect(state.state.observations.filter(row=>row.patient_id===patientId&&row.instrument==='NRS')).toEqual(originalPain);
  await page.reload(); await expect(score).toHaveValue('0');
  await expect(panel.getByRole('img',{name:/계단 오를 때 불편함 경과/})).toBeVisible();
  await score.fill('7');
  await action(page.request,'observation.save',{visitId,...saved,value:3});
  await expect.poll(async()=>(await readState(page.request)).state.observations.filter(row=>row.activity_key==='stairs_up').at(-1)?.value).toBe(3);
  await expect(score).toHaveValue('7');
  await expect(panel.locator('.hs-nrs-summary > div').first().locator('strong')).toContainText('3');
  await panel.getByRole('button',{name:'저장',exact:true}).click();
  await expect.poll(async()=>(await readState(page.request)).state.observations.filter(row=>row.activity_key==='stairs_up').at(-1)?.value).toBe(7);
  await score.fill('11'); await expect(panel.getByRole('button',{name:'저장',exact:true})).toBeDisabled();
  await score.fill('2.5'); await expect(panel.getByRole('button',{name:'저장',exact:true})).toBeDisabled();
  await page.reload(); await expect(score).toHaveValue('7');
  if(process.env.HANI_VISUAL_OUTPUT_DIR) await page.screenshot({path:`${process.env.HANI_VISUAL_OUTPUT_DIR}/stairs-discomfort.png`,fullPage:true});
  await page.goto(`/clinic/patients/${patientId}/progress`);
  await expect(page.getByRole('heading',{name:'계단 오르기 불편',exact:true})).toBeVisible();
  await page.setViewportSize({width:1024,height:900});await page.goto(`/clinic/visits/${visitId}`);
  await expect(panel).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  const { current_visit_id: childVisit }=scenario(initial,'B'); await page.goto(`/clinic/visits/${childVisit}`);
  await expect(page.getByRole('region',{name:'계단 오를 때 불편함',exact:true})).toHaveCount(0);
});
