import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import fixture from './__fixtures__/dual-transcription.json';
const mocks=vi.hoisted(()=>({diarize:vi.fn(),content:vi.fn(),roles:vi.fn(),soap:vi.fn()}));
vi.mock('./transcribe',()=>({transcribeAudio:mocks.diarize,transcribeContentAudio:mocks.content}));
vi.mock('@/lib/audio/storage',()=>({readAudio:async()=>new Blob(['synthetic'])}));
vi.mock('./provider',()=>({inferSpeakerRoles:mocks.roles,generateSoap:mocks.soap,proposeCorrections:vi.fn()}));
import { readState, updateState } from '@/lib/server/store';
import { transcribeStep, soapStep } from './pipeline';
import { POST as review } from '@/app/api/jobs/review/route';
import { unlock, SESSION_COOKIE } from '@/lib/server/auth';
let directory:string;
beforeEach(async()=>{
 directory=await mkdtemp(path.join(os.tmpdir(),'hani-dual-store-'));
 vi.stubEnv('HANI_STORAGE_MODE','local');vi.stubEnv('HANI_DATA_DIR',directory);vi.stubEnv('VERCEL','');vi.stubEnv('NODE_ENV','test');vi.stubEnv('APP_ORIGIN','http://localhost:3000');vi.stubEnv('DEMO_PIN_HASH','');
 mocks.diarize.mockResolvedValue({text:fixture.diarized.map(s=>s.text).join('\n'),segments:fixture.diarized,rawSpeakers:{},model:'gpt-4o-transcribe-diarize'});
 mocks.content.mockResolvedValue({text:fixture.content,model:'gpt-transcribe'});
 mocks.roles.mockResolvedValue({A:{role:'patient',source:'inferred'},B:{role:'clinician',source:'inferred'}});
 mocks.soap.mockImplementation(async(segments)=>({sections:{s:'오늘 통증 5점',o:'',a:'',p:'침 치료 계획'},evidence:[{section:'s',segment_id:segments[2].id,quote:segments[2].text}],warnings:[],followup_questions:[]}));
});
afterEach(async()=>{vi.unstubAllEnvs();await rm(directory,{recursive:true,force:true});});
it('stores immutable original results, preserves group provenance through human review, and uses reviewed text for SOAP',async()=>{
 const initial=await readState();const visitId=initial.state.scenario_inputs[0].current_visit_id;
 const recordingId=randomUUID(),jobId=randomUUID(),now=new Date().toISOString();
 await updateState(state=>{
  state.recordings.push({id:recordingId,clinic_id:state.clinic.id,visit_id:visitId,source:'upload',filename:'test.wav',mime_type:'audio/wav',size_bytes:9,object_path:'test',status:'uploaded',created_at:now});
  state.jobs.push({id:jobId,clinic_id:state.clinic.id,visit_id:visitId,recording_id:recordingId,kind:'transcription',status:'queued',stage:'queued',input_hash:'synthetic-dual',created_at:now,updated_at:now,result:{}});
 });
 const transcriptId=await transcribeStep(jobId);const completed=await readState();
 const job=completed.state.jobs.find(item=>item.id===jobId)!;
 const raw=completed.state.transcripts.find(item=>item.id===transcriptId)!;
 const originals=completed.state.transcripts.filter(item=>item.id===job.result?.diarizedTranscriptId||item.id===job.result?.contentTranscriptId);
 expect(originals).toHaveLength(2);expect(raw.revision).toBe(3);
 expect(raw.text).toBe(fixture.content);expect(raw.segments.map(s=>s.speaker)).toEqual(['patient','clinician','patient','clinician','patient','clinician','patient','clinician']);
 expect(raw.segments[0].source_segment_ids?.length).toBeGreaterThan(1);
 const headers={origin:'http://localhost:3000',host:'localhost:3000','content-type':'application/json'};
 const session=await unlock(new Request('http://localhost:3000/api/access/unlock',{method:'POST',headers}),'1234');
 const response=await review(new Request('http://localhost:3000/api/jobs/review',{method:'POST',headers:{...headers,cookie:`${SESSION_COOKIE}=${session.token}`},body:JSON.stringify({jobId,expectedTranscriptRevision:raw.revision,speakerGroups:{A:'guardian'}})}));
 expect(response.status).toBe(200);const reviewedId=(await response.json()).transcriptId;
 const checked=await readState();const checkedTranscript=checked.state.transcripts.find(item=>item.id===reviewedId)!;
 expect(checkedTranscript.revision).toBe(4);expect(checkedTranscript.segments[0].speaker).toBe('guardian');
 expect(checkedTranscript.segments[0].source_segment_ids).toEqual(raw.segments[0].source_segment_ids);
 await soapStep(jobId);
 expect(mocks.soap.mock.calls.at(-1)![0][0].speaker).toBe('guardian');
 const after=await readState();
 expect(after.state.transcripts.filter(item=>originals.some(o=>o.id===item.id))).toEqual(originals);
 for(const approved of initial.state.soap_documents.filter(item=>item.status==='approved'))expect(after.state.soap_documents.find(item=>item.id===approved.id)).toEqual(approved);
});
